#! /bin/sh
### BEGIN INIT INFO
# Provides:          cstbox-mqtt
# Required-Start:    $remote_fs $syslog cstbox-dbus cstbox-evtmgr
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CSTBox MQTT gateway
# Description:       This package adds a gateway between the CSTBox framework internal
#                    message bus and a MQTT based external one.
### END INIT INFO

# Author: Eric Pascual <eric.pascual@cstb.fr>

DESC="CSTBox MQTT gateway"
INIT_SEQ=94
NAME=cstbox-mqtt
DAEMON=/opt/cstbox/bin/mqttgwd.py
DAEMON_ARGS=
INIT_VERBOSE=yes

. /opt/cstbox/lib/init/init-functions

